- name: Install dependencies
  run: |
    chmod +x /metrics/source/app/action/index.mjs

    # Update and install required packages
    apt-get update
    apt-get install -y wget gnupg ca-certificates libgconf-2-4

    # Add Google Chrome repository and install Chrome
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    apt-get update
    apt-get install -y --fix-broken google-chrome-stable fonts-ipafont-gothic \
      fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      libx11-xcb1 libxtst6 lsb-release --no-install-recommends

    # Install additional tools and dependencies
    apt-get install -y --fix-broken curl unzip
    curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh
    apt-get install -y --fix-broken ruby-full git g++ cmake pkg-config libssl-dev
    gem install licensed
    apt-get install -y --fix-broken python3

    # Clean up
    rm -rf /var/lib/apt/lists/*

    # Install Node.js dependencies and build
    npm ci
    npm run build
